# Generated by Django 3.0.3 on 2020-02-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=1000)),
                ('completed', models.BooleanField(default=False, verbose_name='whether todo is completed')),
                ('completed_at', models.DateTimeField(default=None, verbose_name='Datetime when todo is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime when todo is created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datetime when todo is updated')),
                ('image_url', models.TextField(verbose_name='Image that will be uploaded')),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
